import Head from "next/head";
import Main from "./main/index";
import Header from "../src/presenter/header/index";
import Footer from "../src/presenter/footer/index";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main />
    </>
  );
}
